CREATE TABLE IF NOT EXISTS public.task
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp(6) without time zone,
    description character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    task_status integer,
    updated_at timestamp(6) without time zone,
    CONSTRAINT task_pkey PRIMARY KEY (id)
)